### ISSUE TITLE
Add CodeBehind Framework information.

### ISSUE THREAD

**Issue by elanatframework** [meysamhadeli/awesome-dotnet-tips#26]
Please add the [CodeBehind Framework](https://github.com/elanatframework/Code_behind) and put information about installing, configuring, and developing with it in the new md file.

CodeBehind is a new framework based on ASP.NET Core published by [Elanat](https://elanat.net).

![ASP.NET Core web frameworks list](https://github.com/the-benchmarker/web-frameworks/assets/111444759/4a6de8a8-41fb-4784-abb2-7de82da16648)

According to the latest tests of the Elanat team, the CodeBehind framework is up to 40% faster than the default ASP.NET Core frameworks (ASP.NET Core MVC and Razor Pages).
[Performance test, ASP.NET Core MVC and Razor Pages vs CodeBehind Framework in version 2.2](https://github.com/elanatframework/Code_behind/blob/elanat_framework/doc/performance_test_asp_dot_net_core_mvc_and_razor_pages_vs_code_behind_framework_version_2.2.md)

GitHub link:
https://github.com/elanatframework/Code_behind

**Comment by meysamhadeli** [comment]
Hi, 
Please create a pull request to add this topic to specific and related section. and if you couldn't find related section for that, please close your issue.
Thanks.
